import {NextResponse} from 'next/server';
import {sameOrigin,cookie} from '../../../lib/studio';
export const dynamic='force-dynamic';
function result(data:unknown,status=200){return NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function session(data:any){const response=result({ok:true});response.cookies.set('glaral_access',data.access_token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:data.expires_in||3600});response.cookies.set('glaral_refresh',data.refresh_token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30});return response;}
export async function GET(r:Request){try{const url=process.env.SUPABASE_URL!,key=process.env.SUPABASE_PUBLISHABLE_KEY!,access=cookie(r,'glaral_access'),refresh=cookie(r,'glaral_refresh');if(!access&&!refresh)return result({signedIn:false});if(access){const user=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+access},cache:'no-store'});if(user.ok)return result({signedIn:true});}if(refresh){const response=await fetch(url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh}),cache:'no-store'});const data=await response.json();if(response.ok)return session(data);}return result({signedIn:false});}catch{return result({signedIn:false});}}
export async function POST(r:Request){try{if(!sameOrigin(r))return result({error:'Invalid origin.'},403);const raw=await r.text();if(raw.length>4000)return result({error:'Invalid request.'},400);const b=JSON.parse(raw);if(b.action==='signout'){const response=result({ok:true});response.cookies.delete('glaral_access');response.cookies.delete('glaral_refresh');return response;}
if(b.action!=='signin'||typeof b.email!=='string'||typeof b.password!=='string'||b.email.toLowerCase()!==process.env.ADMIN_EMAIL?.toLowerCase())return result({error:'Use the studio owner account.'},403);
const response=await fetch(process.env.SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:process.env.SUPABASE_PUBLISHABLE_KEY!,'Content-Type':'application/json'},body:JSON.stringify({email:b.email,password:b.password}),cache:'no-store'});const data=await response.json();if(!response.ok)return result({error:'Could not sign in. Check your existing Glaral email and password.'},401);return session(data);
}catch{return result({error:'Sign-in is temporarily unavailable.'},503);}}
