export type Project = {slug:string;name:string;category:string;tagline:string;description:string;status:string;pricing:string;url:string;art:string;color:string;features:string[];checkoutUrl?:string;price?:string};
export type Post = {id:string;title:string;body:string;category:string;date:string;source?:string;project?:string};
export const defaultProjects:Project[] = [
{slug:'prompt-studio',name:'Prompt Studio',category:'Tools',tagline:'Give your next idea a better beginning.',description:'Build a clear, structured prompt for your preferred AI assistant. Choose your task, audience and tone, then copy a practical starting point. Runs entirely in your browser.',status:'Live',pricing:'Free',url:'/prompt-studio#prompt-tool',art:'prompt',color:'mint',features:['Four practical task templates','Audience and tone controls','One-click prompt copy','No account or API needed']},
{slug:'udhar',name:'Udhar',category:'Apps',tagline:'Keep the money. Lose the awkwardness.',description:'A simple personal ledger for money you lend and receive. Keep a clear history, see balances by person, and share a reminder when you choose.',status:'Beta',pricing:'Free',url:'/udhar',art:'ledger',color:'mint',features:['Per-person balances','Dated transaction history','JSON backup and restore','Optional WhatsApp reminders']},
{slug:'splitvideo',name:'SplitVideo',category:'Tools',tagline:'One video. More possibilities.',description:'Split, crop and resize your videos with a browser-based creator tool. Turn longer footage into formats that fit the places you post.',status:'Live',pricing:'Free',url:'https://splitvideo-web.vercel.app',art:'video',color:'lilac',features:['Split longer footage','Crop for different formats','Resize your videos','Browser-based workflow']},
{slug:'ncr-drive',name:'NCR Drive',category:'Games',tagline:'Your next turn is in Delhi.',description:'An evolving Delhi-NCR driving game. Explore the current build and follow the journey toward richer traffic, missions and mobile controls.',status:'Beta',pricing:'Free',url:'https://ncr-drive.vercel.com',art:'drive',color:'peach',features:['Play the current web build','Delhi-NCR direction','Driving gameplay','Work in progress']},
{slug:'cosmic-drop',name:'Cosmic Drop',category:'Games',tagline:'Small planets. One more drop.',description:'A physics merge puzzle project: drop, combine and build a bigger cosmic collection. A project preview while the launch destination is being confirmed.',status:'Coming soon',pricing:'Free',url:'',art:'cosmic',color:'yellow',features:['Physics merge concept','Portrait-first direction','Space-inspired visuals','Launch link coming soon']},
{slug:'creator-workbench',name:'Creator Workbench',category:'Software',tagline:'Less busywork. More creating.',description:'A proposed paid creator workspace for reusable content systems. The product, price and checkout are still being shaped; no purchases are available yet.',status:'Coming soon',pricing:'Paid',url:'',art:'workbench',color:'blue',features:['Paid product concept','Reusable creator workflows','Pricing to be announced','No subscription commitment yet']}
];
// Editorial starter cards are explicitly labelled; they are not the founder's claimed observations.
export const defaultPosts:Post[]=[
{id:'starter-1',title:'The best AI workflow starts with a small problem.',body:'Choose one repetitive task. Describe the input, the output and what a good result looks like. Test it on something real before adding another step.',category:'AI notes',date:'2026-10-06',project:'starter'},
{id:'starter-2',title:'Build a tool you would actually open tomorrow.',body:'A narrow useful tool is easier to test than a giant platform. Start with one job, make the first result clear, and watch where people get stuck.',category:'Building',date:'2026-10-06',project:'starter'},
{id:'starter-3',title:'One recording can become several useful edits.',body:'Start with the moments that stand on their own. Split the footage, choose the right crop, then check each clip before you publish.',category:'Creators',date:'2026-10-06',project:'starter'}
];
