import 'server-only';
import {createHash} from 'node:crypto';
import {defaultProjects,defaultPosts} from './catalogue';
export function sameOrigin(r:Request){const o=r.headers.get('origin');return !!o&&o===new URL(r.url).origin;}
export function safeUrl(value:string){if(!value)return '';if(/^\/[a-zA-Z0-9/_#?.=%-]*$/.test(value)&&!value.startsWith('//'))return value;try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}}
export function cookie(r:Request,key:string){const value=r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(key+'='))?.slice(key.length+1);return value?decodeURIComponent(value):'';}
export async function rpc(r:Request,action:string,payload:unknown={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_PUBLISHABLE_KEY,secret=process.env.GLARAL_BACKEND_SECRET;if(!url||!key||!secret)throw Error('Studio configuration unavailable');const headers:Record<string,string>={'apikey':key,'Content-Type':'application/json'};const token=cookie(r,'glaral_access');if(token)headers.Authorization='Bearer '+token;const response=await fetch(url+'/rest/v1/rpc/glaral_studio_api',{method:'POST',headers,body:JSON.stringify({p_secret:secret,p_action:action,p_payload:payload}),cache:'no-store'});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.message||'Studio request failed'),{status:response.status});return data;}
export async function catalogue(r:Request){const visitor=cookie(r,'glaral_visitor');const data=await rpc(r,'read',{visitor:/^[a-f0-9-]{36}$/.test(visitor)?visitor:null});const overrides=new Map<string,any>(data.projects.map((p:any)=>[p.slug,p]));const projects=defaultProjects.map(p=>overrides.get(p.slug)||p);for(const [slug,p]of overrides)if(!defaultProjects.some(x=>x.slug===slug))projects.push(p);return {...data,projects,posts:data.posts.length?data.posts:defaultPosts};}
export function rateKey(r:Request,visitor:string){const ip=r.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||visitor;return createHash('sha256').update((process.env.GLARAL_BACKEND_SECRET||'')+ip).digest('hex')+':'+Math.floor(Date.now()/60000);}
